version: '3.7'

# If you face issues running the `docker-compose up` command.
# Please refer to the README file of the front-end and back-end applications.

services:
  strategists-web:
    container_name: strategists-web
    platform: linux/amd64
    build:
      context: web
      dockerfile: Dockerfile
    env_file:
      - shared/secrets/web.env.list
    ports:
      - "3000:80"
    depends_on:
      - strategists-service
    networks:
      - strategists-network
  
  strategists-service:
    container_name: strategists-service
    platform: linux/amd64
    build: 
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - shared/secrets/server.env.list
    networks:
      - strategists-network
    volumes:
      - ./shared:/app/shared

networks:
  strategists-network:
    driver: bridge
    