server:
  port: 8090
spring:
  application:
    name: strategists-service
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 64
      connection-timeout: 120000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
strategists:
  game:
    default-map: india
    dice-size: 6
    rent-factor: 0.2
    code-length: 4
    min-players-count: 2
    max-players-count: 6
  configuration:
    clean-up:
      enabled: true
      delay: 300000
      thread-pool-size: 2
    sse-ping:
      enabled: false 
    skip-player:
      enabled: true
      allowed-count: 3
      timeout: 60000
      thread-pool-size: 4
  prediction:
    enabled: true
    python:
      executable: ../prediction/.venv/bin/python
      script: ../prediction/main.py
    export:
      directory: ../prediction/out/
      file-name: classifier.pkl
    train:
      command: train
      directory:
        data: ../prediction/data/
        metadata: ../prediction/metadata/
    predict:
      command: predict
      directory:
        test: ../prediction/test/
  google:
    recaptcha:
      api-url: https://www.google.com/recaptcha/api/siteverify
      secret-key:
    utils:
      credentials-json-file:
      python:
        executable: ../google-utils/.venv/bin/python
        script: ../google-utils/main.py
      permissions:
        command: permissions
        export:
          directory: ../google-utils/
          file-name: permissions.json
        spreadsheet:
          id: 
          range: 
      predictions:
        command: predictions
        download:
          sub-command: download
          drive-folder-id: 
        upload: 
          sub-command: upload
          drive-folder-id: 
