server:
  port: 8090
spring:
  application:
    name: strategists-service
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 64
      connection-timeout: 120000
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: ${ENABLE_H2_CONSOLE:false}
strategists:
  game:
    default-map: india
    dice-size: 6
    rent-factor: 0.2
    code-length: 4
    min-players-count: 2
    max-players-count: 6
  configuration:
    sse-ping:
      enabled: ${ENABLE_SSE_PING:true}
    clean-up:
      enabled: ${ENABLE_CLEAN_UP:true}
      delay: 300000
      thread-pool-size: 2
    skip-player:
      enabled: ${ENABLE_SKIP_PLAYER:true}
      allowed-count: 3
      timeout: 90000
      thread-pool-size: 4
  permissions:
    health-check:
      bypass-for-testing: false
      api-endpoint: ${PERMISSIONS_API_HOST:http://localhost:8001}/health
    google-recaptcha:
      bypass-for-testing: false
      api-endpoint: ${PERMISSIONS_API_HOST:http://localhost:8001}/api/google-recaptcha-verify
    permission-group:
      bypass-for-testing: false
      api-endpoint: ${PERMISSIONS_API_HOST:http://localhost:8001}/api/permission-group
  storage:
    health-check:
      bypass-for-testing: false
      api-endpoint: ${STORAGE_API_HOST:http://localhost:8002}/health
    download:
      bypass-for-testing: false
      api-endpoint: ${STORAGE_API_HOST:http://localhost:8002}/api/download
    upload:
      bypass-for-testing: false
      api-endpoint: ${STORAGE_API_HOST:http://localhost:8002}/api/upload
  predictions:
    enabled: ${ENABLE_PREDICTIONS:true}
    data-directory: ${PREDICTIONS_DATA_DIR:../resources/data}
    google-drive:
      download-folder-id: ${PREDICTIONS_DOWNLOAD_FOLDER_ID:}
      upload-folder-id: ${PREDICTIONS_UPLOAD_FOLDER_ID:}
    strategies:
      train-on-startup-enabled: ${ENABLE_PREDICTIONS_TRAIN_ON_STARTUP:true}
      train-on-end-enabled: ${ENABLE_PREDICTIONS_TRAIN_ON_END:true}
      data-export-enabled: ${ENABLE_PREDICTIONS_DATA_EXPORT:true}
      data-integrity-validation-enabled: ${ENABLE_PREDICTIONS_DATA_INTEGRITY_VALIDATION:true}
      model-inference-enabled: ${ENABLE_PREDICTIONS_MODEL_INFERENCE:true}
    health-check:
      bypass-for-testing: false
      api-endpoint: ${PREDICTIONS_API_HOST:http://localhost:8003}/health
    get-model:
      bypass-for-testing: false
      api-endpoint: ${PREDICTIONS_API_HOST:http://localhost:8003}/api/predictions-model/{game_map_id}
    train-model:
      bypass-for-testing: false
      api-endpoint: ${PREDICTIONS_API_HOST:http://localhost:8003}/api/predictions-model/{game_map_id}/train
    infer-model:
      bypass-for-testing: false
      api-endpoint: ${PREDICTIONS_API_HOST:http://localhost:8003}/api/predictions-model/{game_map_id}/infer
  advice:
    enabled: ${ENABLE_ADVICES:true}
    data-directory: ${ADVICES_DATA_DIR:../resources/advices/}
    google-drive:
      upload-folder-id: ${ADVICES_UPLOAD_FOLDER_ID:}
    frequently-invest:
      enabled: ${ENABLE_FREQUENTLY_INVEST_ADVICE:true}
      priority: 3
      turn-look-back: 3
    avoid-timeout:
      enabled: ${ENABLE_AVOID_TIMEOUT_ADVICE:true}
      priority: 1
    significant-investments:
      enabled: ${ENABLE_SIGNIFICANT_INVESTMENTS_ADVICE:true}
      priority: 2
      min-average-ownership: 50
    concentrate-investments:
      enabled: ${ENABLE_CONCENTRATE_INVESTMENTS_ADVICE:true}
      priority: 2
      min-investments-count: 3
    potential-bankruptcy:
      enabled: ${ENABLE_POTENTIAL_BANKRUPTCY_ADVICE:true}
      priority: 1
