server:
  port: 8090
spring:
  application:
    name: strategists-service
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 64
      connection-timeout: 120000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: ${ENABLE_H2_CONSOLE:false}
strategists:
  game:
    default-map: india
    dice-size: 6
    rent-factor: 0.2
    code-length: 4
    min-players-count: 2
    max-players-count: 6
  configuration:
    sse-ping:
      enabled: ${ENABLE_SSE_PING:true}
    clean-up:
      enabled: ${ENABLE_CLEAN_UP:true}
      delay: 300000
      thread-pool-size: 2 
    skip-player:
      enabled: ${ENABLE_SKIP_PLAYER:true} 
      allowed-count: 3
      timeout: 90000
      thread-pool-size: 4
  prediction:
    enabled: ${ENABLE_PREDICTIONS:true}
    python:
      executable: ../prediction/.venv/bin/python
      script: ../prediction/main.py
    export:
      directory: ../shared/model/
      file-name: classifier.pkl
    train:
      command: train
      directory:
        data: ../shared/data/
        metadata: ../shared/metadata/
    predict:
      command: predict
      directory:
        test: ../shared/test/
  advice:
    enabled: ${ENABLE_ADVICES:true}
    frequently-invest:
      enabled: ${ENABLE_FREQUENTLY_INVEST_ADVICE:true}
      priority: 1
      turn-look-back: 3
  google:
    recaptcha:
      api-url: https://www.google.com/recaptcha/api/siteverify
      secret-key: ${GOOGLE_RECAPTCHA_SECRET_KEY:}
    utils:
      credentials-json-file: ${GOOGLE_CREDENTIALS_JSON:}
      python:
        executable: ../google-utils/.venv/bin/python
        script: ../google-utils/main.py
      permissions:
        bypass-google-sheets-query-for-testing: false
        command: permissions
        export:
          directory: ../shared/secrets/
          file-name: permissions.json
        spreadsheet:
          id: ${GOOGLE_SPREADSHEET_ID:}
          range: ${GOOGLE_SPREADSHEET_RANGE:}
      predictions:
        bypass-google-drive-sync-for-testing: false
        command: predictions
        download:
          sub-command: download
          drive-folder-id: ${GOOGLE_DRIVE_DOWNLOAD_FOLDER_ID:}
        upload: 
          sub-command: upload
          drive-folder-id: ${GOOGLE_DRIVE_UPLOAD_FOLDER_ID:}
