server:
  port: 8090
spring:
  application:
    name: strategists-service
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 64
      connection-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
strategists:
  prediction:
    enabled: true
    export-data-directory: ../prediction/data/
    model-out-directory: ../prediction/out/
    predict-file-directory: ../prediction/temp/
    python-executable: ../prediction/.venv/bin/python
    python-script: ../prediction/main.py
  game:
    default-map: india
    dice-size: 6
    rent-factor: 0.2
  configuration:
    sse-ping:
      enabled: false 
    skip-player:
      enabled: true
      allowed-count: 3
      timeout:
        value: 60
        unit: SECONDS
  security:
    allowed-emails:
    google-recaptcha:
      api-url: https://www.google.com/recaptcha/api/siteverify
      secret-key:   
