[project]
name = "storage"
version = "0.1.0"
description = "The Strategists Storage API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
]
