[dev]
  targetPort = 3000

[build]
  base = "web/"
  publish = "build/"

[[edge_functions]]
  pattern = "/api/games/(.*)/sse"
  function = "proxy-sse"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
